### ISSUE TITLE
NPM install individual fonts

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow-fonts#2]
Regarding GDPR compliance, does an approach like https://github.com/fontsource/fontsource work? 

It's a directory of open source fonts, that are each hosted individually on NPM. 

https://github.com/fontsource/font-files

https://github.com/fontsource/font-files/tree/main/fonts/other/bravura

See directions for installing Bravura via NPM:
https://fontsource.org/fonts/bravura/install

We could try to use fontsource and make sure all the font files are the most up to date versions (I see their version of Bravura might be slightly outdated...).

Or we can take the same approach and publish all the vexflow compatible fonts as individual NPM packages.

Then a developer can run `npm install @vexflow-fonts/leland` to install the web font locally in their project. Then, when your project goes live, your bundler will put the font files on your own web server. Since it is self hosted, you can control the GDPR compliance.

_Originally posted by @ronyeh in https://github.com/0xfe/vexflow/discussions/1577#discussioncomment-6419451_

**Comment by ronyeh** [comment]
We can also contribute to fontsource:

https://github.com/fontsource/font-files/blob/main/CONTRIBUTING.md

**Comment by ronyeh** [comment]
@rvilarl OK, I am going to restructure this repository (since it is not used yet).

I am going to take the same approach as fontsource. 

Each font will be an individual NPM package scoped under `@vexflow-fonts`, and then we will have VexFlow 5 include all our standard fonts (e.g., Bravura) via npm install. Then a developer can choose to add more fonts if desired by doing the same thing (e.g., `npm install @vexflow-fonts/xxxxxx`)

**Comment by rvilarl** [comment]
@ronyeh what about just providing the woff2? Also please include the recommended text fonts.

**Comment by ronyeh** [comment]
FYI, Leland specifies this as the text font:

https://github.com/MuseScoreFonts/Leland/blob/3d51788d76dce449bafe424b1bea77bb9305affb/leland_metadata.json#L25-L31

```js
        "textFontFamily": [
            "Edwin",
            "Century Schoolbook",
            "C059",
            "Academico",
            "serif"
        ],
```

I'll try my best to get the text fonts, and if they are sharable I'll put them up on NPM for our use.

**Comment by ronyeh** [comment]
Here is Edwin: https://github.com/MuseScoreFonts/Edwin/

It's also SIL Open Font, so I'll add it to our repo.

**Comment by ronyeh** [comment]
I'm (slowly) uploading the fonts as individual NPM packages:

https://www.npmjs.com/org/vexflow-fonts

**Comment by ronyeh** [comment]
FYI: You can now npm install a bunch of SMuFL compatible fonts. For example:

```
npm install @vexflow-fonts/finalemaestro
npm install @vexflow-fonts/finalemaestrotext
```

I learned that **Finale Maestro Text** is the font for displaying regular text characters (to be paired with **Finale Maestro**).

Note that this naming convention is different from **Bravura Text** and **Petaluma Text**, which are music fonts meant to be used in a word processor or on a blog.

**Comment by ronyeh** [comment]
See here for the current (still incomplete) list of fonts: https://www.npmjs.com/org/vexflow-fonts

After you npm install a few, you'll find a directory named `@vexflow-fonts/` inside `node_modules/`:

This directory contains one sub directory for each font you installed.

Now, how do we get the font into your app (or VexFlow)? There are a few ways:

1. For local testing, you could reference the `index.css` and font files inside the `node_modules/@vexflow-fonts/<fontname>` directories directly. Quick and dirty, but not ideal....
2. For deployment, you could import these packages into your code, and your bundler (webpack, esbuild, etc.) might be able to work some magic to make the font available on your webapp.
3. Since they are all NPM packages, it means they are also hosted on unpkg or jsdelivr. For example: 
    - https://unpkg.com/@vexflow-fonts/finalemaestrotext@1.0.0/index.css
    - https://unpkg.com/@vexflow-fonts/bravura@1.0.1/index.css
    This is not so different from the vexflow-fonts URLs we had before. 
4. There are probably other ways to use these fonts....
